name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Restart with PM2
        run: |
          sudo npm install -g pm2
          if pm2 describe mean-backend > /dev/null; then
            pm2 restart mean-backend
          else
            pm2 start npm --name mean-backend -- start
          fi
          pm2 save
